CREATE DATABASE NEW_MER
USE NEW_MER

CREATE DATABASE MER_TRAVEL
USE MER_TRAVEL

CREATE TABLE Autor (
Id INT PRIMARY KEY,
Nombre VARCHAR (45),
Apellido VARCHAR (45)
);

CREATE TABLE Libro (
ISBN BIGINT PRIMARY KEY,
Editorial_Id INT,
Titulo VARCHAR (45),
Sinopsis TEXT,
N_Paginas VARCHAR (45)
);

CREATE TABLE Editorial (
Id INT PRIMARY KEY,
Nombre VARCHAR (45),
Sede VARCHAR (45)
);

CREATE TABLE Autor_Has_Libro (
    Autor_Id INT not null FOREIGN KEY REFERENCES Autor(Id),
	Libro_ISBN BIGINT NOT NULL FOREIGN KEY REFERENCES Libro(ISBN),
	
	CONSTRAINT PK_Autor_Has_Libro PRIMARY KEY (Autor_id, Libro_ISBN),
);